# Generated by Django 4.2.7 on 2023-12-01 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AutoMobileApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Mobile',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Vehicle_No',
            new_name='vehicle_No',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='is_WorkManager',
            new_name='is_manager',
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ManagerId', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=50)),
                ('Aadhar_No', models.CharField(max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
