# Generated by Django 4.2.7 on 2023-12-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoMobileApp', '0003_schedules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('reply', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
